# Generated by Django 2.0.7 on 2019-09-15 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='last_name',
            new_name='username',
        ),
    ]
